# Generated by Django 4.0.4 on 2022-05-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='user_pictures')),
            ],
        ),
    ]
