# Generated by Django 3.2.14 on 2022-07-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='addition0',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='addition1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='addition2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='addition3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='addition4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='addition5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='addition6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='addition7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='addition8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='addition9',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
