# Generated by Django 3.2.14 on 2022-07-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0006_auto_20220731_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.CharField(max_length=1000),
        ),
    ]
