# Generated by Django 3.2.14 on 2022-08-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0008_alter_card_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_settings',
            name='plan_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
