# Generated by Django 3.2.14 on 2022-08-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0012_alter_card_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='box',
        ),
    ]
