# Generated by Django 3.2.14 on 2022-08-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0013_remove_card_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_settings',
            name='reviewing_intensity',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=255),
        ),
        migrations.AlterField(
            model_name='review_settings',
            name='selected_voca',
            field=models.CharField(choices=[('elementary', '기초 영단어'), ('K_SAT', '수능 영단어'), ('GRE', '편입/GRE 영단어'), ('all', '모든 영단어'), ('confusing', '혼동하기 쉬운 영단어')], max_length=255),
        ),
    ]
