# Generated by Django 3.2.14 on 2022-08-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0017_completed_dates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='completed_dates',
        ),
    ]
