# Generated by Django 4.0.4 on 2022-04-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voca', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
                ('sentences', models.CharField(max_length=100)),
                ('significance', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('genre', models.CharField(default='GRE', max_length=10)),
            ],
        ),
    ]
