# Generated by Django 4.0.4 on 2022-05-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='learn_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voca_per_day', models.CharField(choices=[('100개', 100), ('200개', 200), ('300개', 300)], max_length=4)),
            ],
        ),
    ]
