# Generated by Django 4.0.4 on 2022-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_learn_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='learn_review_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voca_per_day', models.CharField(choices=[(10, 10), (20, 20), (30, 30), (50, 50), (70, 70), (80, 80), (90, 90), (100, 100), (130, 130), (150, 150), (200, 200), (250, 250), (300, 300)], help_text='하루 동안 외울 단어의 수를 입력하세요.', max_length=10)),
                ('review_day', models.CharField(choices=[('elementary', '기초 영단어'), ('K_SAT', '수능 영단어'), ('GRE', '편입, 토플, GRE 영단어'), ('hard', '고급 영단어'), ('confusing', '혼동하기 쉬운 영단어'), ('idiom', '숙어'), ('all', '모든 영단어')], help_text='외운 단어의 복습이 시작될 주기를 입력하세요. ex) 1,3,7 등', max_length=10)),
                ('select_genre', models.CharField(choices=[('elementary', '기초 영단어'), ('K_SAT', '수능 영단어'), ('GRE', '편입, 토플, GRE 영단어'), ('hard', '고급 영단어'), ('confusing', '혼동하기 쉬운 영단어'), ('idiom', '숙어'), ('all', '모든 영단어')], help_text='외울 단어의 카테고리를 설정하세요. ex) 모든 단어, 수능 단어, 고급 단어, 기초 단어 등', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='learn_review',
        ),
    ]
